/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package InternalPages;

import java.awt.Color;
import javax.swing.plaf.basic.BasicInternalFrameUI;

/**
 *
 * @author canaz
 */
public class dashboardpage extends javax.swing.JInternalFrame {

    private javax.swing.JDesktopPane parentDesktop;

    /**
     * Creates new form dashboardpage
     */
    public dashboardpage() {
        this(null);
    }
    
    public dashboardpage(javax.swing.JDesktopPane parentDesktop) {
        this.parentDesktop = parentDesktop;
        initComponents();
        
        this.setBorder(javax.swing.BorderFactory.createEmptyBorder(0,0,0,0));
        BasicInternalFrameUI bi;
        bi = (BasicInternalFrameUI)this.getUI();
        bi.setNorthPane(null);      
    }
    Color navcolor = new Color(255,0,204);
    Color headcolor = new Color(255,0,255);
    Color bodycolor = new Color(255,153,255);
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        manageUser = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        settings = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 0, 255));
        jPanel1.setLayout(null);

        jPanel3.setBackground(new java.awt.Color(255, 153, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconFolder/icons8-shoes-50.png"))); // NOI18N
        jPanel3.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 170, 160));

        jPanel1.add(jPanel3);
        jPanel3.setBounds(540, 20, 170, 160);

        jLabel1.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jLabel1.setText("InventoryManagementSystem");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(10, 10, 360, 70);

        jLabel4.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel4.setText("SHOE'S STORE");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(10, 70, 160, 30);

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 780, 210));

        jPanel2.setBackground(new java.awt.Color(255, 153, 255));
        jPanel2.setLayout(null);

        manageUser.setBackground(new java.awt.Color(255, 0, 255));
        manageUser.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                manageUserMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                manageUserMouseExited(evt);
            }
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                manageUserMouseClicked(evt);
            }
        });
        manageUser.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("ALL STOCKS");
        manageUser.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, 170, 40));

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconFolder/icons8-stocks-50.png"))); // NOI18N
        manageUser.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 170, 160));

        jPanel2.add(manageUser);
        manageUser.setBounds(180, 30, 170, 160);

        settings.setBackground(new java.awt.Color(255, 0, 255));
        settings.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                settingsMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                settingsMouseExited(evt);
            }
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                settingsMouseClicked(evt);
            }
        });
        settings.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconFolder/logout.png"))); // NOI18N
        settings.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 170, 160));

        jLabel8.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("RETURN");
        settings.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 170, 40));

        jPanel2.add(settings);
        settings.setBounds(420, 30, 170, 160);

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 210, 780, 230));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void manageUserMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_manageUserMouseEntered
       manageUser.setBackground(navcolor);
    }//GEN-LAST:event_manageUserMouseEntered
       
    private void manageUserMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_manageUserMouseExited
        manageUser.setBackground(headcolor);
    }//GEN-LAST:event_manageUserMouseExited

    private void settingsMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_settingsMouseEntered
        settings.setBackground(navcolor);
    }//GEN-LAST:event_settingsMouseEntered

    private void settingsMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_settingsMouseExited
        settings.setBackground(headcolor);
    }//GEN-LAST:event_settingsMouseExited

    private void manageUserMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_manageUserMouseClicked
        // open Products page as internal frame
        productsPage pp = new productsPage(parentDesktop);
        if(parentDesktop != null) {
            parentDesktop.add(pp);
            pp.setVisible(true);
        } else {
            pp.setLocationRelativeTo(null);
            pp.setVisible(true);
        }
    }//GEN-LAST:event_manageUserMouseClicked

    private void reportsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_reportsMouseClicked
        reports r = new reports(); r.setLocationRelativeTo(null); r.setVisible(true);
    }//GEN-LAST:event_reportsMouseClicked

    private void settingsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_settingsMouseClicked
        // Close this dashboardpage and go back to home
        this.dispose();
    }//GEN-LAST:event_settingsMouseClicked

    private void addDataMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addDataMouseEntered
        addData.setBackground(navcolor);
    }//GEN-LAST:event_addDataMouseEntered

    private void addDataMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addDataMouseExited
        addData.setBackground(headcolor);
    }//GEN-LAST:event_addDataMouseExited

    private void addDataMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addDataMouseClicked
        addItem();
    }//GEN-LAST:event_addDataMouseClicked

    private void addItem(){
        try{
            String name = javax.swing.JOptionPane.showInputDialog(this, "Item name:"); if(name==null || name.trim().isEmpty()) return;
            String qtyS = javax.swing.JOptionPane.showInputDialog(this, "Quantity:"); if(qtyS==null) return; int qty = Integer.parseInt(qtyS.trim());
            String priceS = javax.swing.JOptionPane.showInputDialog(this, "Price (₱):"); if(priceS==null) return; priceS = priceS.replaceAll("[^0-9.\\-]", ""); double price = Double.parseDouble(priceS.trim());
            java.io.File dir = new java.io.File("db"); if(!dir.exists()) dir.mkdirs();
            java.io.File f = new java.io.File(dir, "items.csv");
            if(!f.exists()){
                try(java.io.BufferedWriter bw = new java.io.BufferedWriter(new java.io.FileWriter(f,true))){ bw.write("1,Sample Item A,10,9.99"); bw.newLine(); bw.write("2,Sample Item B,5,19.99"); bw.newLine(); }
            }
            // find max id
            int maxId=0; try(java.io.BufferedReader br = new java.io.BufferedReader(new java.io.FileReader(f))){ String line; while((line=br.readLine())!=null){ String[] p=line.split(","); if(p.length>0){ try{ maxId = Math.max(maxId, Integer.parseInt(p[0].trim())); }catch(NumberFormatException ex){} } } }
            int id = maxId+1; String date = java.time.LocalDate.now().toString();
            try(java.io.BufferedWriter bw = new java.io.BufferedWriter(new java.io.FileWriter(f,true))){ bw.write(id+","+name.trim()+","+qty+","+price+","+date); bw.newLine(); }
            javax.swing.JOptionPane.showMessageDialog(this, "Item added.");
        }catch(Exception e){ javax.swing.JOptionPane.showMessageDialog(this, "Invalid input: "+e.getMessage()); }
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel manageUser;
    private javax.swing.JPanel settings;
    // End of variables declaration//GEN-END:variables
}
