/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package InternalPages;

import javax.swing.JOptionPane;

/**
 *
 * @author canaz
 */
public class Landpage extends javax.swing.JFrame {

    /**
     * Creates new form Landpage
     */
    public Landpage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        arrowBtn = new javax.swing.JPanel();
        arrowLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Ejane Inventory Management System");
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 0, 204));
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Century Gothic", 1, 24));
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("WELCOME TO EJANE INVENTORY MANAGEMENT SYSTEM");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(10, 50, 750, 50);

        arrowBtn.setBackground(new java.awt.Color(0, 0, 0));
        arrowBtn.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        arrowBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                arrowBtnMouseClicked(evt);
            }
        });
        arrowBtn.setLayout(null);

        arrowLabel.setFont(new java.awt.Font("Century Gothic", 1, 48));
        arrowLabel.setForeground(new java.awt.Color(255, 255, 255));
        arrowLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        arrowLabel.setText(">");
        arrowLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        arrowLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                arrowLabelMouseClicked(evt);
            }
        });
        arrowBtn.add(arrowLabel);
        arrowLabel.setBounds(10, 5, 40, 60);

        jPanel1.add(arrowBtn);
        arrowBtn.setBounds(370, 200, 60, 70);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 770, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void arrowBtnMouseClicked(java.awt.event.MouseEvent evt) {
        new loginForm().setVisible(true);
        this.dispose();
    }

    private void arrowLabelMouseClicked(java.awt.event.MouseEvent evt) {
        arrowBtnMouseClicked(evt);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Landpage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Landpage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Landpage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Landpage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }

        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Landpage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel arrowBtn;
    private javax.swing.JLabel arrowLabel;
    // End of variables declaration//GEN-END:variables
}
